build for wetc
wrappedether/canonical-wetc pull request #2
Opened 2022-05-04 03:05 UTC by l303l

2022-05-04 19:18 UTC, gitr0n1n requested changes
networks.json
Ethereum Classic Networks:
ETC Mainnet = "61"
KOT Kotti = "6"
METC Mordor = "63" 
TETC Morden = "62"

Source: https://chainlist.org/

2022-05-04 19:25 UTC, gitr0n1n commented
> networks.json Ethereum Classic Networks: ETC Mainnet = "61" KOT Kotti = "6" METC Mordor = "63" TETC Morden = "62"
> 
> Source: https://chainlist.org/

Looks like Morden was replaced by Mordor. So only three active networks for ETC.
Source: http://ethereumclassic.org/development/testnets

2022-05-04 19:27 UTC, gitr0n1n approved these changes
LGTM

2022-05-05 15:40 UTC, ETCSecurity commented on build/contracts/WETC9.json
>    "deployedSourceMap": "718:1809:1:-;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1289:9;:7;:9::i;:::-;718:1809;739:40;;8:9:-1;5:2;;;30:1;27;20:12;5:2;739:40:1;;;;;;;;;;;;;;;
Does this need to be changed @l303l ?

2022-05-05 15:40 UTC, ETCSecurity commented on build/contracts/WETC9.json
>    "deployedSourceMap": "718:1809:1:-;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1289:9;:7;:9::i;:::-;718:1809;739:40;;8:9:-1;5:2;;;30:1;27;20:12;5:2;739:40:1;;;;;;;;;;;;;;;
Point has been clarified. Resolving issue.

2022-05-05 15:41 UTC, ETCSecurity approved these changes

2022-05-05 15:45 UTC, merged